version: "3.8"
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-storage:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  mongodb-storage:
    name: mongodb-storage
    
